name: 'Pagar.me Demo Conventional Standards'
description: 'Utility with some conventional patterns for deploying branch-versioned services'
branding:
  icon: 'command'
  color: 'green'
inputs:
  environment:
    description: 'Environment slug'
    required: true
  version-file:
    description: 'Version file location'
    required: true
  version-key:
    description: 'Version object key location'
    default: "version"
    required: true
  container-registry:
    description: 'Docker container registry URL'
    required: true
  charts-path:
    description: 'Charts path prefix'
    default: './'
    required: false
outputs:
  environment:
    description: 'Environment slug'
  version:
    description: 'Version from version file'
  project-name:
    description: 'Project slug'
  project-url:
    description: 'Project url'
  short-sha:
    description: 'Short commit sha'
  container-registry:
    description: 'Docker container registry URL'
  container-repository:
    description: 'Repository name, {project-name}-{environment}'
  container-tag:
    description: 'Project tag, {version}-{short-sha}'
  container-url:
    description: 'Concatenate {container-registry}/{container-repository}'
  container-image:
    description: 'Concatenate {container-url}:{container-tag}'
  chart-location:
    description: 'Chart location in charts folder'
  container-registry-escaped:
    description: 'Escape version for output container-registry'
  container-repository-escaped:
    description: 'Escape version for output container-repository'
  container-url-escaped:
    description: 'Escape version for output container-url'
  container-tag-escaped:
    description: 'Escape version for output container-tag'
  container-image-escaped:
    description: 'Escape version for output container-image'
  project-url-escaped:
    description: 'Escape version for output project-url'
runs:
  using: 'node12'
  main: 'dist/index.js'
